### ISSUE TITLE
Filter sensitive data in parameters in request params

### ISSUE THREAD

**Issue by andreapavoni** [romul/airbrake-elixir#6]
Hi there, thank you for this useful package :-)

I've installed `airbrake-elxir` on a phoenix app where I've already configured `Phoenix.Logger` to [filter parameters](https://hexdocs.pm/phoenix/Phoenix.Logger.html) such as `password`, `token`, etc.

However, in error notifications I still see the values of these parameters.

Is it possible to have a similar mechanism for notices sent by `airbrake-elixir`?

Thanks in advance

**Comment by romul** [comment]
@andreapavoni Good idea! Take a look at https://github.com/romul/airbrake-elixir/commit/84e97e59e95b1a83b450c73eb3aa10691a1d5f2c

**Comment by andreapavoni** [comment]
Very cool, thanks!
